trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*

variables:
  foo: bar

pool:
  vmImage: ubuntu-16.04

steps:
  - script: |
      echo "Build.Reason: $(Build.Reason)"
      echo "Build.Repository.LocalPath: $(Build.Repository.LocalPath)"
      echo "Build.SourceBranch: $(Build.SourceBranch)"
      echo "System.PullRequest.SourceBranch: $(System.PullRequest.SourceBranch)"
      echo "System.PullRequest.TargetBranch: $(System.PullRequest.TargetBranch)"
    displayName: 'echoing vars'

